apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: manipal2209/capstone_01_image:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80
